### ISSUE TITLE
Vision/Auto

### ISSUE THREAD

**Issue by JoeJanickiChSh** [chopshop-166/frc-2023#1]
- [x] Combine vision pose estimation with odometry
- [x] Add `driveTo` command
- [x] Add `driveToNearestPosition` command
- [x] Get all the axes flopped and swapped correctly
- [x] Get proper rotation filtering
- [x] Get drivePID actually working
- [x] #34

**Comment by msoucy** [comment]
Closing - auto paths is a separate task now
