### ISSUE TITLE
Balance Base 

### ISSUE THREAD

**Issue by Hsaunders603** [chopshop-166/frc-2023#10]
Need help debugging. Currently, I have:
```


public void balance() {
        double angleStuff = Gyro.getAngle();
        //^^Lets pretend this works
        if (angleStuff > 0){
           Drive.drive(0.5, 0, 0);
        }
        else if(angleStuff < 0){
            Drive.drive(0.5, 0, 0);
        }
        
    }
```

**Comment by msoucy** [comment]
I suggest taking a look at [this thread](https://www.chiefdelphi.com/t/warning-to-everyone-working-on-auto-balance/422460) for some thoughts from the community.

Some of the classes in [here](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/controller/package-summary.html) might be helpful.

**Comment by Hsaunders603** [comment]
Update: It now looks like this:
```
public CommandBase balance() {
        return cmd("balance").onInitialize(() -> { 
            double wiggleStatus = wiggleBot.getPitch();
            if (Math.abs(wiggleStatus)< 2){
                return;
            }
            move(0.3, 0, 0);
        }).runsUntil(() -> Math.abs(0 - wiggleBot.getPitch()) < 3 );
    }
```

**Comment by msoucy** [comment]
How does this handle both forward and reverse?

**Comment by Hsaunders603** [comment]
I'm not sure it does.
Helen S

**Comment by Hsaunders603** [comment]
- [x] Actually do an analysis of if balancing is worth it
- [x] Write a paragraph about it so I have proof
- [x] Talk about it with people

**Comment by Hsaunders603** [comment]
Soo... Long story short, trying really hard to balance in Autonomous isn't worth it. If we just move into position: 
A. It should be balanced enough (they seem easy to balance) 
B. Even if we can't engage, we are only "missing" 4 points. Scoring a middle game piece would make up for that, and if we only dock we still get points, where as if we don't try for an extra piece, we might miss the mobility points and game piece points, and if we don't successfully engage it won't be worth it.
We can still do a really rough version, but trying to have super fine-tuned stuff won't be worth it.
