### ISSUE TITLE
Command list

### ISSUE THREAD

**Issue by Lucimoot** [chopshop-166/frc-2023#18]
add the commands for your subsystem here to allow for drafting of a keymap.

**Comment by Lucimoot** [comment]
Intake
- Cone Grab
- Cone Release
- Cube Grab
- Cube Release
- Sensor Grab

**Comment by JoeJanickiChSh** [comment]
## Drive

- Drive with the joysticks (`drive`)
- Line up with nearest scoring position (`driveToNearest`)
- Rotate to face driver station (takes in joystick positions in order to continue driving while doing the rotation) (`rotateToAngle`)

**Comment by Finn6360** [comment]
- Move are to...
- Extend arm
- Move Arm

**Comment by Lucimoot** [comment]
Co-Pilot Keymap:
![Co-PilotRev3](https://user-images.githubusercontent.com/114252157/217675803-381745c8-9553-42d8-848f-f19d8e2aad65.png)

Driver Keymap:
![Driver Keymap](https://user-images.githubusercontent.com/114252157/217673927-c80f4b63-eee7-4223-ad89-422239d438d4.png)

Blank Keymap:
![Blank Keymap RB](https://user-images.githubusercontent.com/114252157/217673928-72c57354-b386-4caf-804d-72724734f009.png)

**Comment by msoucy** [comment]
This will need to be updated (again) after integration is merged

**Comment by msoucy** [comment]
Closing this, the info is now on the wiki
