### ISSUE TITLE
current year robot motors

### ISSUE THREAD

**Issue by Liammurray19** [chopshop-166/frc-2023#19]
purpose | motor | Type | PDH slot
-- | -- | -- | --
drive back right | 1 | Sparkmax | 1
steering back right | 2 | Sparkmax | 0
canCoder back right | 1 | CanCoder |  
drive back left | 3 | Sparkmax | 19
steering back left | 4 | Sparkmax | 18
canCoder back left | 2 | CanCoder |  
drive front right | 5 | Sparkmax | 3
steer front right | 6 | Sparkmax | 2
canCoder front right | 3 | CanCoder |  
drive front left | 7 | Sparkmax | 17
steer front left | 8 | Sparkmax | 16
canCoder front left | 4 | CanCoder |  
intake claw | 9 | Talon SRX | 14
arm rotation | 10 | Sparkmax | 4
arm extension | 11 | Sparkmax | 13
Gyro | 1 | Pigeon |  
Pnumatic hub | 1 | Pnumatics | 15

**Comment by msoucy** [comment]
Apparently the intake claw is a Talon. Task for early 2/11 is to determine if it's a Talon FX or Talon SRX, attached via PWM or CAN.

**Comment by TimB-87** [comment]
Just updated it do be Talon SRX. It is attached via CAN.

**Comment by msoucy** [comment]
Closed via #27
