### ISSUE TITLE
Telescoping Arm Extension

### ISSUE THREAD

**Issue by TimB-87** [chopshop-166/frc-2023#3]
- [x] Create motor object
- [x] Command to extend arm manually
- [x] Command to extend arm with a bang-bang controller
- [x] Command to extend arm with PID
- [x] Command to move to each scoring location
- [x] Soft limit command
- [x] safeState command
- [x] Create ArmMap
- [x] Test bang-bang controller
- [x] Test PID controller
- [x] Merge with Finn
- [x] #21
- [ ] More testing
- [ ] Tune extension motion

**Comment by bot190** [comment]
We also need to prevent the arm from crashing the arm into the ground. Specifically the minimum angle will vary depending on how far the arm is extended. This will be very important to ensure we don't damage the robot.
