### ISSUE TITLE
Refine work for week 5

### ISSUE THREAD

**Issue by Hsaunders603** [chopshop-166/frc-2023#43]
- [x] Presets 
- [x]  Ground cube pickup
- [x]  Check stow retract 
- [ ] Refine other pickup presets  
- [x] Check that intake spins when we want it to? Same with stow
- [ ] PID

**Comment by TimB-87** [comment]
- [x] Fix stow retract completely

**Comment by TimB-87** [comment]
We kind of did ground cube pickup yesterday, but once the absolute encoder for arm rotate is on, we have to redo all presets
